WebApplication2/Controllers/MinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class MinesController : Controller
    {
        // GET: Mines
        ApplicationDbContext ob = new ApplicationDbContext();
        public ActionResult Index()
        {
            
            var userID = this.User.Identity.GetUserId();
            var user = ob.Users.Find(userID);
            var city = user.Cities.First();
            this.UpdteResources(city);
            return View(city);


        }
        private void UpdteResources(City city)
        {
            var start = DateTime.Now;
            foreach (var res in city.Resources)
            {
                foreach (var mine in city.Mines)
                {
                    if (mine.Type == res.Type)
                    {
                        res.Value += mine.GetProductionPerHour() * (start - res.LastUpdate).TotalHours;
                    }
                }
                res.LastUpdate = start;
            }
            ob.SaveChanges();

        }

        public ActionResult Details(int mineID)
        {
            var userID = this.User.Identity.GetUserId();
            var user = ob.Users.Find(userID);
            var city = user.Cities.First();
            var mine = ob.Mines.Find(mineID);
            return View (mine);
        }
        [HttpPost]
        public ActionResult Upgrade (int mineID, bool fastUpgrade)
        {
            var mine = ob.Mines.Find(mineID);
            var city = mine.City;
            var needed = mine.getUpgradeRequirements();
            var have = city.Resources;

            if(fastUpgrade)
            {
                needed = needed.Select(n => (amount: n.amount * 10, type: n.type)).ToArray();
            }

            var r = needed
                .Join(have, n => n.type, h => h.Type, (n, h) => (needed: n, have: h));

            if (!r.All(_ => _.needed.amount > _.have.Value))
            {
                return View(new MessageViewModel
                {
                    Message = $"You do not have enough resources"
                });

            }

            foreach (var item in r)
            {
                item.have.Value -= item.needed.amount;
            }
            var amounts = needed.Select(n => n.amount);
            mine.Level++;
            mine.UpgradeCompletesAt = DateTime.Now.AddHours(0.5 * mine.Level);

            this.ob.SaveChanges();
            return View(new MessageViewModel
            {
                Message = $"Mine id = {mineID}{fastUpgrade}"
            });
        }
    }
}

WebApplication2/Views/Mines/Details.cshtml
@model WebApplication2.Models.Mine

@{
    ViewBag.Title = "Details";
    this.Layout = null;
}

@if (this.Model.Type == WebApplication2.Models.ResourceType.Clay)
{
    <img src="~/Content/img/mine-@(this.Model.Type).png">
    <p>Clay is produced here. By increasing its level, you increase the clay production.</p>
    <p> Current level: @(Model.Level) and production: @(Model.Level * 13);</p>
    <p> Next level: @(Model.Level + 1)and production: @((Model.Level + 1) * 13);</p>
}
else if (this.Model.Type == WebApplication2.Models.ResourceType.Wood)
{
    <img src="~/Content/img/mine-@(this.Model.Type).png">
    <p> The woodcutter cuts down trees in order to produce lumber. The further you extend the woodcutter, the more lumber is produced</p>    
    <p> Current level: @(Model.Level) and production: @(Model.Level*13);</p>
    <p> Next level: @(Model.Level + 1)and production: @((Model.Level+1)* 13);</p>
    

}
else if (this.Model.Type == WebApplication2.Models.ResourceType.Wheat)
{
    <img src="~/Content/img/mine-@(this.Model.Type).png">
    <p>
        Your population`s food is produced here. By increasing the farm`s level, you increase its crop production.
    </p>
    <p> Current level: @(Model.Level) and production: @(Model.Level * 13);</p>
    <p> Next level: @(Model.Level + 1)and production: @((Model.Level + 1) * 13);</p>

}
else if (this.Model.Type == WebApplication2.Models.ResourceType.Iron)
{
    <img src="~/Content/img/mine-@(this.Model.Type).png">
    <p>
        Here miners produce the precious resource of iron. By increasing the mine`s level, you increase the iron production.
        Add Comment
    </p>
    <p> Current level: @(Model.Level) and production: @(Model.Level * 13);</p>
    <p> Next level: @(Model.Level + 1)and production: @((Model.Level + 1) * 13);</p>
}

@using (Html.BeginForm("Upgrade","Mines"))
{
    @Html.HiddenFor(m=>m.MineID)
    <div> Do a fast upgrade?: @Html.CheckBox("fastUpgrade")</div>
    //<input name="mineID" value="10" type="hidden" />
    <button type="submit">Upgrade</button>
}

WebApplication2/Views/Mines/Index.cshtml
@model WebApplication2.Models.City

@{
    ViewBag.Title = "Index";
}
<table>
       <tr>
           @foreach (var res in this.Model.Resources)
           {
             
             <td class="res-img @(res.Type)"><img src="~/Content/img/icon-@(res.Type).png"></td>
             <td>@res.Type</td>
             <td class="res-value @(res.Type)">@res.Value.ToString("n4")</td>
             <td class="res-update @(res.Type)">@res.LastUpdate</td>
            //<td>@Html.ActionLink("Details", "Details", new { mineID = res.MineID })</td>

           }
       </tr>
</table>
<table class="mines">
    @foreach (var mine in this.Model.Mines)
    {
        <tr class="@(mine.Type)">

            <td><img src="~/Content/img/icon-@(mine.Type).png"></td>
            <td>@mine.Type</td>
            <td>@mine.Level</td>
            <!-- <td>@Html.ActionLink("Details", "Details", new { mineID = mine.MineID })</td> -->
            <td><span class="mine-details-btn" data-mine-id="@mine.MineID">Details</span></td>
            <td class="hourProduction">@mine.GetProductionPerHour()</td>
        </tr>
    }
    <div id="mine-details-container">
        <div class="close-btn">X</div>
        <div class="content"></div>
    </div>
</table>
@section Scripts
{
    <script src="~/Scripts/Fisiere/JavaScript.js"></script>
    <script src="~/Scripts/Date.min.js"></script>
}

WebApplication2/Views/Mines/Upgrade.cshtml
@{
    ViewBag.Title = "Upgrade";
}

<h2>@this.Model.Message</h2>